name: flutter_foreground_task
description: This plugin is used to implement a foreground service on the Android platform.
version: 3.7.1
homepage: https://github.com/Dev-hwang/flutter_foreground_task

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.flutter_foreground_task
        pluginClass: FlutterForegroundTaskPlugin
      ios:
        pluginClass: FlutterForegroundTaskPlugin
